name: Auto Deploy to PyPI

on:
  push:
    branches: [ main ]
    paths:
      - 'vdw_surfgen/**'
      - 'setup.py'
      - 'pyproject.toml'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
      test_pypi:
        description: 'Deploy to TestPyPI instead of PyPI'
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install deployment dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r deploy_requirements.txt
    
    - name: Configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Run automated deployment
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        TWINE_REPOSITORY_URL: ${{ github.event.inputs.test_pypi == 'true' && 'https://test.pypi.org/legacy/' || 'https://upload.pypi.org/legacy/' }}
      run: |
        BUMP_TYPE="${{ github.event.inputs.bump_type || 'patch' }}"
        TEST_PYPI_FLAG="${{ github.event.inputs.test_pypi == 'true' && '--test-pypi' || '' }}"
        
        python auto_deploy.py --$BUMP_TYPE $TEST_PYPI_FLAG --skip-tests
    
    - name: Create GitHub Release
      if: success()
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.NEW_VERSION }}
        release_name: Release v${{ env.NEW_VERSION }}
        body: |
          Automated release v${{ env.NEW_VERSION }}
          
          Changes:
          - Auto-generated release from commit ${{ github.sha }}
        draft: false
        prerelease: false
